db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url: postgres:5234
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
#spring.profiles.active: web


logging:
  level:
    org.springframework.web: DEBUG
    root: INFO
    org.alexsandrov.spring.database.pool.ConnectionPool: info
    org.springframework.jdbc.core: TRACE
  file:
    name: alexsandrov.log
    #рутовая директория проекта
    path: /


spring:
  mvc:
    view:
      prefix: /WEB_INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: root
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: none





